# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VAssist.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JarvisUI(object):
    def setupUi(self, JarvisUI):
        JarvisUI.setObjectName("JarvisUI")
        JarvisUI.resize(1997, 1075)
        self.centralwidget = QtWidgets.QWidget(JarvisUI)
        self.centralwidget.setObjectName("centralwidget")
        self.Bg_2 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_2.setGeometry(QtCore.QRect(10, 20, 771, 511))
        self.Bg_2.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.Bg_2.setText("")
        self.Bg_2.setObjectName("Bg_2")
        self.Bg_3 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_3.setGeometry(QtCore.QRect(790, 20, 791, 511))
        self.Bg_3.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.Bg_3.setText("")
        self.Bg_3.setObjectName("Bg_3")
        self.Gif_1 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_1.setGeometry(QtCore.QRect(30, 40, 731, 471))
        self.Gif_1.setText("")
        self.Gif_1.setPixmap(QtGui.QPixmap("B.G/Iron_Template_1.gif"))
        self.Gif_1.setScaledContents(True)
        self.Gif_1.setObjectName("Gif_1")
        self.Gif_2 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_2.setGeometry(QtCore.QRect(810, 40, 751, 471))
        self.Gif_2.setText("")
        self.Gif_2.setPixmap(QtGui.QPixmap("ExtraGui/live.gif"))
        self.Gif_2.setScaledContents(True)
        self.Gif_2.setObjectName("Gif_2")
        self.Gif_3 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_3.setGeometry(QtCore.QRect(-20, 570, 701, 401))
        self.Gif_3.setText("")
        self.Gif_3.setPixmap(QtGui.QPixmap("VoiceReg/Aqua.gif"))
        self.Gif_3.setScaledContents(True)
        self.Gif_3.setObjectName("Gif_3")
        self.Bg_4 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_4.setGeometry(QtCore.QRect(1600, 20, 311, 261))
        self.Bg_4.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.Bg_4.setText("")
        self.Bg_4.setObjectName("Bg_4")
        self.Gif_4 = QtWidgets.QLabel(self.centralwidget)
        self.Gif_4.setGeometry(QtCore.QRect(1620, 40, 271, 221))
        self.Gif_4.setText("")
        self.Gif_4.setPixmap(QtGui.QPixmap("ExtraGui/Earth.gif"))
        self.Gif_4.setScaledContents(True)
        self.Gif_4.setObjectName("Gif_4")
        self.Bg_1 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_1.setGeometry(QtCore.QRect(-10, -120, 2071, 1301))
        self.Bg_1.setText("")
        self.Bg_1.setPixmap(QtGui.QPixmap("B.G/Black_Template.jpg"))
        self.Bg_1.setScaledContents(True)
        self.Bg_1.setObjectName("Bg_1")
        self.Text_Time_1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Time_1.setGeometry(QtCore.QRect(1410, 800, 451, 141))
        self.Text_Time_1.setStyleSheet("background-color: Transparent;\n"
"color: rgb(0, 85, 255);\n"
"border-radius: 0;")
        self.Text_Time_1.setObjectName("Text_Time_1")
        self.Bg_5 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_5.setGeometry(QtCore.QRect(1360, 760, 561, 221))
        self.Bg_5.setText("")
        self.Bg_5.setPixmap(QtGui.QPixmap("B.G/frame2.PNG"))
        self.Bg_5.setScaledContents(True)
        self.Bg_5.setObjectName("Bg_5")
        self.Bg_6 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_6.setGeometry(QtCore.QRect(1360, 540, 561, 221))
        self.Bg_6.setText("")
        self.Bg_6.setPixmap(QtGui.QPixmap("B.G/frame2.PNG"))
        self.Bg_6.setScaledContents(True)
        self.Bg_6.setObjectName("Bg_6")
        self.Text_Time_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Time_2.setGeometry(QtCore.QRect(1410, 580, 451, 141))
        self.Text_Time_2.setStyleSheet("background-color: Transparent;\n"
"color: rgb(0, 85, 255);\n"
"border-radius: 0;")
        self.Text_Time_2.setObjectName("Text_Time_2")
        '''self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(1610, 300, 291, 101))
        self.pushButton_start.setStyleSheet("color: rgb(255, 255, 127);\n"
"color: rgb(0, 170, 255);\n"
"font: 24pt \"Sylfaen\";\n"
"font: 24pt \"MS Reference Sans Serif\";\n"
"font: 22pt \"Mongolian Baiti\";\n"
"background-color: black;")
        self.pushButton_start.setObjectName("pushButton_start")
        self.Bg_7 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_7.setGeometry(QtCore.QRect(1600, 290, 311, 241))
        self.Bg_7.setStyleSheet("\n"
"background-color: rgb(0, 170, 255);")
        self.Bg_7.setText("")
        self.Bg_7.setObjectName("Bg_7")'''
        self.pushButton_end = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_end.setGeometry(QtCore.QRect(1610, 420, 291, 101))
        self.pushButton_end.setStyleSheet("color: rgb(255, 255, 127);\n"
"color: rgb(0, 170, 255);\n"
"font: 24pt \"Sylfaen\";\n"
"font: 24pt \"MS Reference Sans Serif\";\n"
"font: 22pt \"Mongolian Baiti\";\n"
"background-color: black;")
        self.pushButton_end.setObjectName("pushButton_end")
        self.Bg_8 = QtWidgets.QLabel(self.centralwidget)
        self.Bg_8.setGeometry(QtCore.QRect(710, 650, 651, 201))
        self.Bg_8.setText("")
        self.Bg_8.setPixmap(QtGui.QPixmap("B.G/frame2.PNG"))
        self.Bg_8.setScaledContents(True)
        self.Bg_8.setObjectName("Bg_8")
        self.Text_Time_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.Text_Time_3.setGeometry(QtCore.QRect(760, 690, 541, 121))
        self.Text_Time_3.setStyleSheet("background-color: Transparent;\n"
"color: rgb(0, 85, 255);\n"
"border-radius: 0;")
        self.Text_Time_3.setObjectName("Text_Time_3")
        self.Bg_1.raise_()
        #self.Bg_7.raise_()
        self.Bg_5.raise_()
        self.Gif_3.raise_()
        self.Bg_2.raise_()
        self.Bg_3.raise_()
        self.Gif_1.raise_()
        self.Gif_2.raise_()
        self.Bg_4.raise_()
        self.Gif_4.raise_()
        self.Text_Time_1.raise_()
        self.Bg_6.raise_()
        self.Text_Time_2.raise_()
        #self.pushButton_start.raise_()
        self.pushButton_end.raise_()
        self.Bg_8.raise_()
        self.Text_Time_3.raise_()
        JarvisUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(JarvisUI)
        QtCore.QMetaObject.connectSlotsByName(JarvisUI)

    def retranslateUi(self, JarvisUI):
        _translate = QtCore.QCoreApplication.translate
        JarvisUI.setWindowTitle(_translate("JarvisUI", "MainWindow"))
        #self.pushButton_start.setText(_translate("JarvisUI", "Start"))
        self.pushButton_end.setText(_translate("JarvisUI", "End"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JarvisUI = QtWidgets.QMainWindow()
    ui = Ui_JarvisUI()
    ui.setupUi(JarvisUI)
    JarvisUI.show()
    sys.exit(app.exec_())
